### ISSUE TITLE
Comparison chart accuracy

### ISSUE THREAD

**Issue by ocharles** [NorfairKing/sydtest#1]
Hi,

As mentioned on Twitter, here are my thoughts on the comparison chart:

* *Monadic test definition*: I guess, yes, `tasty` doesn't have this as a blessed API, but I'm not sure it warrants a ✖️. Usually if you need to dynamically generate a `TestTree`, you just do that with an `IO TestTree` action, and then pass that into `defaultMain`. For example, see https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/tests/Dhall/Test/TypeInference.hs#L29-L56, where Dhall builds a `TestTree` of essentially a directory of golden files.
* *Parallel test execution*: Tasty supports `-j` which will run tests in parallel
* *Parallel or sequential test-group execution*: Tasty doesn't support marking a particular test group for parallel execution, `-j` is all or nothing.
* *First-class support for pure tests*: There is no test provider for this, though one solution is to use `assertBool` from `tasty-hunit`: `testCase "My test" $ assertBool "f 5 is 42" $ f 5 == 42
* *Source location annotations for tests in test output*: This is not a responsibility of Tasty, it is a responsibility of test providers. tasty-hedgehog for example preserves all the nice formatting you get from Hedgehog, so I think ✖️ is definitely the wrong characteristic. If anything, I'd say N/A
* *Individual test execution timing*: `tasty-stats` is certainly one answer here, but Tasty itself already does timing (it just doesn't display anything for very fast tests)
* *Test suite execution timing*: Tasty does output a summary time for the entire test execution time. Is that what this feature is describing? If so, this is ✔️
* *ppShow instead of show for counterexample output*: Not `tasty`s responsibility, this is up to the test provider. For example, if you use `tasty-hedgehog` and write Hedgehog properties, you'll get Hedgehog's diffing.
* *show for counterexample output*: Similar to above. You've given it a ✔️, but it's not Tasty's job.
* *Fancy Unicode output*: Presumably this is about displaying the information of a particular test. I guess you could say ✖️ because `tasty` just formats the overall test tree in ASCII? I don't really know what this feature is
* *Assertion-specific output with explanation*: I don't know what this is. Is it about being able to write `assertHas foo bar` and getting a nice error message?
* *Coloured diffing*: Doable if that's what a test provider chooses to do. Hedgehog does this, so tasty-hedgehog does this.
* *multi-line diffing*: Similar to above, though I don't know any test providers that do this.
* *Contextual failures*: I don't know what this is
* *Inter-test progress output during test suite execution*: This is supported. https://hackage.haskell.org/package/tasty-hunit-0.10.0.3/docs/Test-Tasty-HUnit.html#v:testCaseSteps is an example of it. This is a feature of `tasty` (see https://hackage.haskell.org/package/tasty-1.4.0.1/docs/Test-Tasty-Providers.html#t:Progress)
* *Intra-test progress output during test suite execution*: I guess also supported by the above? I'm not sure how these differ.
* *Optional standard output and standard error suppression*: Theoretically a provider could use https://hackage.haskell.org/package/silently to do this. For example, `hedgehog-classes` uses this. In practice, it really messes things up, to the point that I'm not sure this is fundamentally possible.
* *Aquire and release a resource for every test in a group (before and after)*: Supported, just use `withResource` on a particular `TestTree` (`withResource` can appear anywhere, not just at the root of the test tree). You can do: `map (\t -> withResource ... t) [ test1, test2, test3 ]`.
* *Wrap a single test to use a withResource-like function (around)*: I think this is supported by the same argument above.
* *Wrap a test group to use a withResource-like function (aroundAll)*: I think this is supported by the same argument above.
* *Randomising execution order*: I think an ingredient could do this, but I can't be certain. Probably fair to leave this as ? for now.
* *Using scarce resources across tests*: Yes, use `withResource`.
* *A way to fail the test suite as soon as one test fails (--fail-fast)*: Possibly doable with an ingredient (c.f., `tasty-rerun`)
* *Pending tests*: Not sure this is something that would be part of Tasty.

Hope this helps. It might seem like I'm being pedantic, but as I've said - a feature comparison chart needs to be honest if people can truly use it to make an assessment.

**Comment by NorfairKing** [comment]
Hi @ocharles ! Thanks for the very detailed issue.
I really don't have too much experience with tasty so this really helps.
I don't mean to be dishonest in the README at all, so I'm going to open a PR with fixes based on this issue for you to review.

**Comment by ocharles** [comment]
Sounds good, loop me in when you're done and I'll be happy to review!

**Comment by NorfairKing** [comment]
@ocharles I think I addressed everything in #2, Have a look whenever convenient, no hurries!

**Comment by NorfairKing** [comment]
I'll mark this as closed for now, feel free to reopen if anything is still inaccurate.
