### ISSUE TITLE
Unclear how to filter for specific test cases

### ISSUE THREAD

**Issue by cdimitroulas** [NorfairKing/sydtest#27]
The docs say:
> Test suites can be filtered using the --match or --filter flags. Empty groups are removed so that their resources are not even set up when there are no tests that need them.

I would be happy to add an example to the docs if you could help me understand how this is supposed to work. I tried `stack test -- --match X` but that failed. What is the correct way to pass this flag?

**Comment by NorfairKing** [comment]
`stack` is not how you invoke the test suite executable. This isn't sydtest related.

You use `stack test --test-arguments="--match X"`.

**Comment by cdimitroulas** [comment]
Would you accept a PR to add an example command using `stack` and `cabal` i.e. `stack test --test-arguments="--match MyTest` and `cabal test --test-option="--match MyTest"`?

**Comment by NorfairKing** [comment]
Sure! Where would you like to add it? In the readme? Go for it!

**Comment by p4l1ly** [comment]
For cabal it is actually `cabal test --test-option="--match" --test-option="MyTest"`

**Comment by cdimitroulas** [comment]
Thanks for the correction @p4l1ly, if you'd like you can open a PR to fix that!
