### ISSUE TITLE
`shouldStartWith` uses `isInfixOf` instead of `isPrefixOf`

### ISSUE THREAD

**Issue by joelfisch** [NorfairKing/sydtest#31]
I just noticed that the following assertion does not fail:

```haskell
"test" `shouldStartWith` "es"
```

After looking at the implementation here https://github.com/NorfairKing/sydtest/blob/b6422a1940372e4670fa628f8d62f0ba6519d867/sydtest/src/Test/Syd/Expectation.hs#L70 it does seem like this is a copy-paste error as it uses `isInfixOf` and even has the error description "has infix" instead of "has prefix" or something like it.

Should I create a PR or am I missing something?

**Comment by NorfairKing** [comment]
Whoops! Jup, a PR would be great!
