### ISSUE TITLE
Black icons in README aren't visible in dark mode

### ISSUE THREAD

**Issue by kquick** [NorfairKing/sydtest#4]
Just a small note that your comparison chart in the README uses black check and cross icons, which are not visible in github's new dark mode, so it makes the  table look largely empty.

**Comment by NorfairKing** [comment]
Thanks for the report. I'll review if this is still a problem in a few months. I expect github to fix this.

**Comment by NorfairKing** [comment]
Looks fixed on my machine.
![fixed](https://user-images.githubusercontent.com/3521180/111676467-7c419000-881e-11eb-94fb-5e92c5816d64.png)
