### ISSUE TITLE
Incorrect printing of Unicode in text of `shouldBe`

### ISSUE THREAD

**Issue by jfaure** [NorfairKing/sydtest#52]
```haskell
it "←“  $ "→“ `shouldBe` "->""
```
the description "←" prints fine, but for Actual and Expected fields the text is shown, resulting in "\8594" instead of "→"

**Comment by NorfairKing** [comment]
@jfaure This may be a wontfix, because `shouldBe` can't know if what you're comparing is text or not.
However, you can throw your own assertion if you like: https://hackage.haskell.org/package/sydtest-0.11.0.0/docs/Test-Syd-Run.html#t:Assertion

**Comment by jfaure** [comment]
Easiest workaround is wrapping the shouldBe args in a newtype
```haskell
newtype UniText = UniText Data.Text.Text deriving Eq
instance Show UniText where show (UniText l) = Data.Text.unpack l
```
