### ISSUE TITLE
junit support

### ISSUE THREAD

**Issue by teto** [NorfairKing/sydtest#84]
I would like to generate junit reports of my tests since those are previewable by gitlab (https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportsjunit) and can also be used by various tools such as https://www.datadoghq.com/ to plot test statistics across time.
For hspec there is https://github.com/freckle/hspec-junit-formatter. Is there a library that adds junit support for sydtest ? junit is an xml format

**Comment by NorfairKing** [comment]
@teto there's no such library atm. PR welcome
