### ISSUE TITLE
Update Hspec comparaison table

### ISSUE THREAD

**Issue by maxigit** [NorfairKing/sydtest#89]
Just discovered the existence of sydtest and read the comparaison with Hspec. There are two features that Hspec does which I think are missing from the table (don't know their status for sydtest)
- focus  via `focus` and `fit`.
- rerun, only rerun the failed test (until all test pass and rerun them all).

Also  hspec `xit` seems to be the exact equivalent to sydtest `pending` ( instead of `it ... pending`).

**Comment by NorfairKing** [comment]
PR welcome. 
`sydtest` also has `xit` btw.
