### ISSUE TITLE
question: tasty/hunit assertEqual and assertFailure - what to replace with in sydtest?

### ISSUE THREAD

**Issue by ketzacoatl** [NorfairKing/sydtest#9]
Hello!

I am updating a library I maintain (consul-haskell) to use sydtest. The existing tests use `assertEqual` and `assertFailure` from `tasty-hunit` - https://www.stackage.org/haddock/lts-17.9/tasty-hunit-0.10.0.3/Test-Tasty-HUnit.html#v:assertFailure and https://www.stackage.org/haddock/lts-17.9/tasty-hunit-0.10.0.3/Test-Tasty-HUnit.html#v:assertEqual. Which functions in sydtest would be reasonable analogs, or should I refactor these more aggressively? I have tried `shouldBe` and `expectationFailure` to start, but I thought it might make sense to ask which you would recommend.

**Comment by NorfairKing** [comment]
@ketzacoatl Yes, `shouldBe` and `expectationFailure` are what you want to be using, see the examples in the docs for `it`.
